# Project
modId=bluemap-better-markers
modName=BlueMap Better Markers
modVersion=1.0.1
modDescription=Improves BlueMap marker rendering by showing coordinates when selected
modAuthor=Jacob Jennings
modLicense=MIT

# Minecraft / Fabric
minecraftVersion=1.21.11
fabricLoaderVersion=0.18.4
fabricApiVersion=0.140.2+1.21.11
fabricKotlinVersion=1.13.0+kotlin.2.1.0

# Dependencies
blueMapApiVersion=2.7.6

# Build
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
kotlin.code.style=official

